//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: stateful.proto
//
//package org.stateful.function.domain;
//
//public interface GreetResponseOrBuilder extends
//    // @@protoc_insertion_point(interface_extends:org.stateful.function.domain.GreetResponse)
//    com.google.protobuf.MessageOrBuilder {
//
//  /**
//   * <code>string who = 1;</code>
//   * @return The who.
//   */
//  String getWho();
//  /**
//   * <code>string who = 1;</code>
//   * @return The bytes for who.
//   */
//  com.google.protobuf.ByteString
//      getWhoBytes();
//
//  /**
//   * <code>string greeting = 2;</code>
//   * @return The greeting.
//   */
//  String getGreeting();
//  /**
//   * <code>string greeting = 2;</code>
//   * @return The bytes for greeting.
//   */
//  com.google.protobuf.ByteString
//      getGreetingBytes();
//}
