// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stateful.proto

package org.stateful.function.domain;

public final class Stateful {
  private Stateful() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stateful_function_domain_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stateful_function_domain_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stateful_function_domain_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stateful_function_domain_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016stateful.proto\022\034org.stateful.function." +
      "domain\"\033\n\014GreetRequest\022\013\n\003who\030\001 \001(\t\".\n\rG" +
      "reetResponse\022\013\n\003who\030\001 \001(\t\022\020\n\010greeting\030\002 " +
      "\001(\tB \n\034org.stateful.function.domainP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_stateful_function_domain_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_stateful_function_domain_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stateful_function_domain_GreetRequest_descriptor,
        new String[] { "Who", });
    internal_static_org_stateful_function_domain_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_stateful_function_domain_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stateful_function_domain_GreetResponse_descriptor,
        new String[] { "Who", "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
